export const USERLOGGEDIN = 'USERLOGGEDIN';
export const REDIRECT = 'REDIRECT';

export const LOGINCHAGED = 'LOGINCHAGED';
export const SUBMITLOGINFORM = 'SUBMITLOGINFORM';



export const REGISTRATION_INIT = 'REGISTRATION_INIT';
export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_POST = 'REGISTRATION_POST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';




export const LOGIN_POST = 'LOGIN_POST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';





export const REGISTRATONCHANGED = 'REGISTRATONCHANGED';
export const SUBMITREGISTRATIONFORM = 'SUBMITREGISTRATIONFORM';

export const GETALLRPODUCTS = 'GETALLRPODUCTS';
